import type { MLModelInfo } from "@/lib/types";

/**
 * Mirror of the real training artifact at
 * `backend/app/ml/models/metrics.json` (generated by `python -m app.ml.train`).
 *
 * These are real values produced by the repository's XGBoost training
 * pipeline on the SYNTHETIC dataset (500 rows, 80/20 split). The mock API
 * serves them so the Model Performance surface reflects the actual saved
 * model instead of fabricated placeholders. Metrics remain clearly labelled
 * as synthetic/demo — never presented as experimental results.
 */
export const mockMLModelInfo: MLModelInfo = {
  trained: true,
  trainedAt: "2026-09-08T10:57:29.561337+00:00",
  datasetRows: 500,
  trainRows: 400,
  testRows: 100,
  featureCount: 25,
  targetCount: 6,
  supportedSubstrates: ["Magnesium", "Aluminum", "Zirconium", "Tantalum"],
  supportedCoatings: [
    "Magnesium",
    "Aluminum",
    "Zirconium",
    "Tantalum",
    "MgO",
    "Al2O3",
    "ZrO2",
    "TiO2",
  ],
  metrics: {
    corrosion_resistance: {
      r2: 0.6909,
      mae: 5.7332,
      rmse: 7.2598,
      mape: 0.5179,
      selected_model: "GradientBoostingRegressor",
    },
    corrosion_rate: {
      r2: 0.882,
      mae: 0.1772,
      rmse: 0.2247,
      mape: 0.4059,
      selected_model: "XGBRegressor",
    },
    coating_thickness: {
      r2: 0.9269,
      mae: 4.1941,
      rmse: 5.4343,
      mape: 0.1003,
      selected_model: "XGBRegressor",
    },
    porosity: {
      r2: 0.8232,
      mae: 1.8831,
      rmse: 2.394,
      mape: 0.376,
      selected_model: "GradientBoostingRegressor",
    },
    pore_size: {
      r2: 0.8836,
      mae: 0.9959,
      rmse: 1.4802,
      mape: 1.0403,
      selected_model: "RandomForestRegressor",
    },
    wear_resistance: {
      r2: 0.843,
      mae: 16.2987,
      rmse: 20.0306,
      mape: 0.144,
      selected_model: "XGBRegressor",
    },
  },
  dataStatus: "synthetic",
  demo: true,
};